USE flight_data;
CREATE TABLE airports(
    airport_id INT AUTO_INCREMENT PRIMARY KEY,
    IATA_CODE VARCHAR(255),
    AIRPORT VARCHAR(255),
    CITY VARCHAR(255),
    STATE VARCHAR(255),
    COUNTRY VARCHAR(255),
    LATITUDE FLOAT(53),
    LONGITUDE FLOAT(53)
);

CREATE TABLE airlines (
    airline_id INT AUTO_INCREMENT PRIMARY KEY,
	IATA_CODE VARCHAR(255),
    AIRLINE VARCHAR(255)
);

CREATE TABLE flights(
    flight_id INT AUTO_INCREMENT PRIMARY KEY,
    A_YEAR INT NULL,
    A_MONTH INT NULL,
    A_DAY INT NULL,
    DAY_OF_WEEK INT NULL,
    AIRLINE VARCHAR(255) NULL,
    FLIGHT_NUMBER INT NULL,
    TAIL_NUMBER VARCHAR(255) NULL,
    ORIGIN_AIRPORT VARCHAR(255) NULL,
    DESTINATION_AIRPORT VARCHAR(255) NULL,
    SCHEDULED_DEPARTURE INT NULL,
    DEPARTURE_TIME INT NULL,
    DEPARTURE_DELAY INT NULL,
    TAXI_OUT INT NULL,
    WHEELS_OFF INT NULL,
    SCHEDULED_TIME INT NULL,
    ELAPSED_TIME INT NULL,
    AIR_TIME INT NULL,
    DISTANCE INT NULL,
    WHEELS_ON INT NULL,
    TAXI_IN INT NULL,
    SCHEDULED_ARRIVAL INT NULL,
    ARRIVAL_TIME INT NULL,
    ARRIVAL_DELAY INT NULL,
    DIVERTED INT NULL,
    CANCELLED INT NULL,
    CANCELLATION_REASON VARCHAR(255) NULL,
    AIR_SYSTEM_DELAY INT NULL,
    SECURITY_DELAY INT NULL,
    AIRLINE_DELAY INT NULL,
    LATE_AIRCRAFT_DELAY INT NULL,
    WEATHER_DELAY INT NULL,
    origin_airport_id INT NULL,
    destination_airport_id INT NULL,
    airline_id INT NULL,
    FOREIGN KEY (origin_airport_id) REFERENCES airports(airport_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (destination_airport_id) REFERENCES airports(airport_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (airline_id) REFERENCES airlines(airline_id) ON DELETE CASCADE ON UPDATE CASCADE
);
   
